// Les Roches - Configuration & disponibilites/prix (Beds24)

const SUPABASE_URL  = 'https://vrufclzcaswkdgrffdwm.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydWZjbHpjYXN3a2RncmZmZHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTE2MjgsImV4cCI6MjA4OTg2NzYyOH0.cHllj6HZms7qf5PVc3LPy057r3rvCv6JyjfAfVlH34E';

/* Fiche villa - calendrier depuis availability.json (Beds24) */
;(function(){function init(){if(!document.getElementById("sb-checkin"))return;var mm=document.documentElement.innerHTML.match(/booking2\.php\?propid=(\d+)/);if(!mm)return;var PROPID=mm[1],TODAY=new Date().toISOString().slice(0,10),availSet=null;function applyAll(){if(!availSet)return;var a=(document.getElementById("sb-checkin")||{}).value||"",b=(document.getElementById("sb-checkout")||{}).value||"",pc=a&&!b;document.querySelectorAll(".lrp-day[data-date]").forEach(function(c){var d=c.getAttribute("data-date");if(!d)return;var ok=pc?(d>a&&availSet.has(d)):(d>=TODAY&&availSet.has(d));if(ok)c.classList.remove("lrp-disabled");else c.classList.add("lrp-disabled");});}var pend=false;function sched(){if(pend)return;pend=true;setTimeout(function(){pend=false;applyAll();},30);}fetch("/availability.json?cb="+Date.now(),{cache:"no-store"}).then(function(r){return r.json();}).then(function(j){var v=j.villas&&j.villas[PROPID];if(!v||!v.available)return;availSet=new Set(v.available);applyAll();new MutationObserver(sched).observe(document.body,{childList:true,subtree:true});}).catch(function(){});}if(document.readyState!=="loading")init();else document.addEventListener("DOMContentLoaded",init);})();

/* Recherche multi-villas (villas.html) - dispos + prix Beds24 (-5% direct) */
;(function(){var M={opale:"326247",onyx:"326248",jade:"326257",topaze:"326251",agate:"326259",ambre:"326258"};var AV=null,DISC=0.95;function fmt(n){return "$"+Math.round(n).toLocaleString("en-US");}function iterOK(pid,ci,co,priceMode){var v=AV.villas[pid]||{};var s=new Set(v.available||[]),pr=v.prices||{};var c=new Date(ci+"T00:00:00"),e=new Date(co+"T00:00:00"),tot=0,n=0;while(c<e){var d=c.getFullYear()+"-"+String(c.getMonth()+1).padStart(2,"0")+"-"+String(c.getDate()).padStart(2,"0");if(!s.has(d))return {ok:false};if(priceMode){if(pr[d]==null)return {ok:false};tot+=pr[d];}n++;c.setDate(c.getDate()+1);}return {ok:true,tot:tot,n:n};}function minPrice(pid){var pr=(AV.villas[pid]||{}).prices||{},m=null;for(var k in pr){if(m==null||pr[k]<m)m=pr[k];}return m;}function enforce(){if(!AV||!document.getElementById("ds-btn"))return;var ci=(document.getElementById("ds-checkin")||{}).value,co=(document.getElementById("ds-checkout")||{}).value;Object.keys(M).forEach(function(sg){var pid=M[sg],card=document.getElementById("vc-"+sg);if(!card)return;var pEl=document.getElementById("price-"+sg),tEl=document.getElementById("total-"+sg);if(ci&&co){var r=iterOK(pid,ci,co,true);if(!r.ok){if(!card.classList.contains("unavail")){card.classList.add("unavail");if(tEl){tEl.textContent="Not available";tEl.style.color="#c0392b";}}}else if(r.n>0){var direct=r.tot*DISC;if(pEl)pEl.textContent=fmt(direct/r.n);if(tEl){tEl.textContent=r.n+"n \u00b7 Total "+fmt(direct);tEl.style.color="";}}}else{var mp=minPrice(pid);if(mp!=null&&pEl)pEl.textContent=fmt(mp*DISC);}});}fetch("/availability.json?cb="+Date.now(),{cache:"no-store"}).then(function(r){return r.json();}).then(function(j){AV=j;}).catch(function(){});setInterval(enforce,400);})();
