// Les Roches - Prix & disponibilites: source unique = Beds24 (availability.json). Site direct = -5% des plateformes.

const SUPABASE_URL  = 'https://vrufclzcaswkdgrffdwm.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydWZjbHpjYXN3a2RncmZmZHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTE2MjgsImV4cCI6MjA4OTg2NzYyOH0.cHllj6HZms7qf5PVc3LPy057r3rvCv6JyjfAfVlH34E';

/* Langue courante -> libelles */
function LR_LANG(){return (document.documentElement.lang||"en").slice(0,2).toLowerCase();}
function LR_NIGHT(){return {fr:"nuit",es:"noche"}[LR_LANG()]||"night";}
function LR_NA(){return {fr:"Non disponible",es:"No disponible"}[LR_LANG()]||"Not available";}

/* ==== Fiche villa: calendrier + prix Beds24 (-5%), instantane ==== */
;(function(){function init(){if(!document.getElementById("sb-checkin"))return;var mm=document.documentElement.innerHTML.match(/booking2\.php\?propid=(\d+)/);if(!mm)return;var PID=mm[1],TODAY=new Date().toISOString().slice(0,10),AV=null,DISC=0.95;function fmt(n){return "$"+Math.round(n).toLocaleString("en-US");}function d2s(c){return c.getFullYear()+"-"+String(c.getMonth()+1).padStart(2,"0")+"-"+String(c.getDate()).padStart(2,"0");}function applyCal(){var V=AV&&AV.villas[PID];if(!V)return;var av=new Set(V.available||[]);var a=(document.getElementById("sb-checkin")||{}).value||"",b=(document.getElementById("sb-checkout")||{}).value||"",pc=a&&!b;document.querySelectorAll(".lrp-day[data-date]").forEach(function(c){var d=c.getAttribute("data-date");if(!d)return;var ok=pc?(d>a&&av.has(d)):(d>=TODAY&&av.has(d));if(ok)c.classList.remove("lrp-disabled");else c.classList.add("lrp-disabled");});}function minP(){var pr=(AV&&AV.villas[PID]||{}).prices||{},m=null;for(var k in pr){if(m==null||pr[k]<m)m=pr[k];}return m;}function calc(ci,co){var V=AV&&AV.villas[PID]||{},pr=V.prices||{},s=new Set(V.available||[]),c=new Date(ci+"T00:00:00"),e=new Date(co+"T00:00:00"),tot=0,n=0;while(c<e){var d=d2s(c);if(!s.has(d)||pr[d]==null)return null;tot+=pr[d];n++;c.setDate(c.getDate()+1);}return {tot:tot,n:n};}function setHTML(el,h){if(el&&el.innerHTML!==h)el.innerHTML=h;}function setTxt(el,t){if(el&&el.textContent!==t)el.textContent=t;}function applyPrice(){if(!AV)return;var pv=document.querySelector(".sb-price-val"),ci=(document.getElementById("sb-checkin")||{}).value||"",co=(document.getElementById("sb-checkout")||{}).value||"";if(ci&&co){var r=calc(ci,co);if(r&&r.n>0){var dir=r.tot*DISC;setHTML(pv,fmt(dir/r.n)+" <small>/ "+LR_NIGHT()+"</small>");setTxt(document.getElementById("sb-total-val"),fmt(dir));setTxt(document.getElementById("bk-sum-total"),fmt(dir));}}else{var mp=minP();if(mp!=null)setHTML(pv,fmt(mp*DISC)+" <small>/ "+LR_NIGHT()+"</small>");}}function all(){applyCal();applyPrice();}fetch("/availability.json?cb="+Date.now(),{cache:"no-store"}).then(function(r){return r.json();}).then(function(j){AV=j;all();new MutationObserver(all).observe(document.body,{childList:true,subtree:true,characterData:true});}).catch(function(){});setInterval(all,300);}if(document.readyState!=="loading")init();else document.addEventListener("DOMContentLoaded",init);})();

/* ==== Recherche multi-villas (villas.html): dispos + prix Beds24 (-5%) ==== */
;(function(){var M={opale:"326247",onyx:"326248",jade:"326257",topaze:"326251",agate:"326259",ambre:"326258"};var AV=null,DISC=0.95;function fmt(n){return "$"+Math.round(n).toLocaleString("en-US");}function iterOK(pid,ci,co,pm){var v=AV.villas[pid]||{};var s=new Set(v.available||[]),pr=v.prices||{};var c=new Date(ci+"T00:00:00"),e=new Date(co+"T00:00:00"),tot=0,n=0;while(c<e){var d=c.getFullYear()+"-"+String(c.getMonth()+1).padStart(2,"0")+"-"+String(c.getDate()).padStart(2,"0");if(!s.has(d))return {ok:false};if(pm){if(pr[d]==null)return {ok:false};tot+=pr[d];}n++;c.setDate(c.getDate()+1);}return {ok:true,tot:tot,n:n};}function minPrice(pid){var pr=(AV.villas[pid]||{}).prices||{},m=null;for(var k in pr){if(m==null||pr[k]<m)m=pr[k];}return m;}function enforce(){if(!AV||!document.getElementById("ds-btn"))return;var ci=(document.getElementById("ds-checkin")||{}).value,co=(document.getElementById("ds-checkout")||{}).value;Object.keys(M).forEach(function(sg){var pid=M[sg],card=document.getElementById("vc-"+sg);if(!card)return;var pEl=document.getElementById("price-"+sg),tEl=document.getElementById("total-"+sg);if(ci&&co){var r=iterOK(pid,ci,co,true);if(!r.ok){if(!card.classList.contains("unavail")){card.classList.add("unavail");if(tEl){tEl.textContent=LR_NA();tEl.style.color="#c0392b";}}}else if(r.n>0){var dir=r.tot*DISC;if(pEl)pEl.textContent=fmt(dir/r.n);if(tEl){tEl.textContent=r.n+"n \u00b7 Total "+fmt(dir);tEl.style.color="";}}}else{var mp=minPrice(pid);if(mp!=null&&pEl)pEl.textContent=fmt(mp*DISC);}});}fetch("/availability.json?cb="+Date.now(),{cache:"no-store"}).then(function(r){return r.json();}).then(function(j){AV=j;}).catch(function(){});setInterval(enforce,400);})();
